matches:
  # Turkish Characters   
  - trigger: "C7"
    replace: "Ç"
        
  - trigger: "c7"
    replace: "ç"

  - trigger: "S7"
    replace: "Ş"
    
  - trigger: "s7"
    replace: "ş"
        
  - trigger: "G7"
    replace: "Ğ"

  - trigger: "g7"
    replace: "ğ"
  
  - trigger: "U7"
    replace: "Ü"
        
  - trigger: "u7"
    replace: "ü"

  - trigger: "O7"
    replace: "Ö"
    
  - trigger: "o7"
    replace: "ö"
        
  - trigger: "I7"
    replace: "İ"

  - trigger: "i7"
    replace: "ı"
